//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InputDialog.rc
//
#define IDOK                            1
#define IDCANCEL                        2
#define IDI_ICON1                       102
#define IDR_TEXT1                       103
#define IDD_INPUTBOX_FileOpen           103
#define IDD_INPUTBOX                    103
#define IDD_DIALOG1                     105
#define IDD_CRASHBOX                    105
#define IDR_RT_MANIFEST1                106
#define IDD_PROCESS                     107
#define IDB_SPLASH_PIC                  112
#define IDR_POPUP_MENU                  113
#define IDD_DIALOG2                     114
#define IDD_PHOTO_FRAME                 114
#define IDD_INPUTBOX1                   115
#define IDD_INPUTBOX_BROWSE             115
#define IDD_UPDATE_BUMPTOP              116
#define IDI_ICON2                       119
#define IDD_THEME_CONFLICT              122
#define IDD_INPUTBOX_AUTHORIZATION      123
#define IDD_INPUTBOX2                   125
#define IDD_FEEDBACK                    126
#define IDD_BREAKPILE                   127
#define IDD_CHANGEICON                  128
#define IDD_UPDATEDRIVERS               129
#define IDD_UPDATEDRIVERS1              130
#define IDD_AUTHFAILED                  130
#define IDD_UPDATEDRIVERS2              131
#define IDD_UPDATEMESSAGE               131
#define IDB_AUTH_HEADER                 132
#define IDD_TWITTER                     133
#define IDD_FACEBOOK_AUTH               134
#define IDD_TWITTER_LOGIN               135
#define IDD_FACEBOOK_CONFIRM            136
#define IDD_AUTHORIZE                   137
#define IDD_AUTHORIZATION_CHOOSE        138
#define IDD_TWITTER_AUTH                139
#define IDD_DEAUTHORIZE_CONFIRM         140
#define IDD_CHOOSE_VERSION              141
#define IDB_CHOOSE_VERSION              142
#define IDB_GET_PRO                     143
#define IDB_GET_PRO_HOVER               144
#define IDB_USE_FREE                    146
#define IDB_USE_FREE_HOVER              147
#define IDB_ACTIVATE                    148
#define IDB_ACTIVATE_HOVER              149
#define IDB_ACTIVATE_DISABLED           150
#define IDB_THANK_YOU                   151
#define IDB_NO_PROBLEM                  152
#define IDD_THANK_YOU                   153
#define IDB_OTHER_GOODNESS              154
#define IDB_BITMAP1                     155
#define IDB_NO_PROBLEM_HOVER            155
#define IDB_CHOOSE_VERSION_EXPIRED      157
#define IDD_EULA                        159
#define IDC_INPUTBOX_PROMPT             1000
#define IDC_THEME_CONFLICT_PROMPT       1000
#define IDC_INPUTBOX_DLG_EDIT1          1001
#define IDC_CRASHBOX_DLG_EDIT           1001
#define IDC_INPUTBOX_DLG_EDIT2          1002
#define IDC_CRASHBOX_PROMPT             1002
#define IDC_PHOTO_LOCAL_DIR             1002
#define IDC_PHOTO_LOCALDIR_TEXT         1002
#define IDC_EDIT1                       1003
#define IDC_CRASHBOX_EMAIL              1003
#define IDC_INPUTBOX_DLG_EDIT3          1003
#define IDC_PHOTO_RSS_FEED_TEXT         1003
#define IDC_PHOTO_RSSFEED_TEXT          1003
#define IDC_TEXT                        1004
#define IDC_MODELESS_PROMPT             1004
#define IDC_PHOTO_FLICKR_TEXT           1004
#define IDC_BROWSE                      1006
#define IDC_BROWSE2                     1007
#define IDC_BROWSE_LOCALDIR             1007
#define IDC_RADIO1                      1008
#define IDC_LOCAL_RADIO                 1008
#define IDC_RADIO2                      1009
#define IDC_INPUTBOX_TEXT               1009
#define IDC_RSS_RADIO                   1009
#define IDC_INPUTBOX_BROWSE_TEXT        1010
#define IDC_FLICKR_RADIO                1010
#define IDC_INPUTBOX_BROWSE_PROMPT      1011
#define IDC_EMAIL_LABEL                 1012
#define IDC_CHECK                       1012
#define IDC_UPDATE_SEND_SCREENSHOT      1012
#define IDC_PHOTO_FRAME                 1013
#define IDC_UPDATE_LABEL                1013
#define IDC_EMAIL_LABEL2                1014
#define IDC_FEEDBACK_LABEL              1014
#define IDC_EMAIL_LABEL3                1015
#define IDC_FEEDBACK_LABEL3             1015
#define IDC_BUTTON1                     1016
#define IDC_PROXYSETTINGS               1016
#define IDC_TEXTBOX                     1017
#define IDC_BUTTON2                     1019
#define IDC_AUTHORIZEMANUALLY           1019
#define IDC_FEEDBACK_TYPE               1020
#define IDC_BUYKEY                      1020
#define IDC_BUYPROKEY                   1020
#define IDC_PROMPT                      1022
#define IDC_FEEDBACK_EMAIL              1024
#define IDC_FEEDBACK_MESSAGE            1025
#define IDC_TWITTER_LOGIN_PASSWORD      1025
#define IDC_FEEDBACK_LABEL2             1027
#define IDC_TWITTER_CHARCOUNT           1028
#define IDC_TWITTER_LOGIN_PASSWORD_LABEL 1028
#define IDC_TWITTER_LOGIN_USERNAME_LABEL 1030
#define IDC_TWITTER_LOGIN_USERNAME      1031
#define IDC_TWITTER_LOGIN_LABEL         1032
#define IDC_TWITTER_LABEL               1033
#define IDC_FREE_RADIO                  1034
#define IDC_PRO_RADIO                   1035
#define IDC_PRO_LEARNMORE               1036
#define IDC_PRO_LABEL                   1037
#define IDC_PRO_INPUT                   1038
#define IDC_AUTHORIZE_FRAME             1039
#define IDC_AUTH_HEADER                 1040
#define IDC_QUESTION                    1042
#define IDC_LEARNMORE                   1043
#define IDC_PIN_TEXT                    1044
#define IDC_SEND_FEEDBACK               1045
#define IDC_RESET_BUMPTOP_SETTINGS      1046
#define IDC_BACKGROUND_IMAGE            1050
#define IDC_PRO_KEY_TEXT_BOX            1053
#define IDC_GET_PRO_BUTTON              1057
#define IDC_USE_FREE_BUTTON             1058
#define IDC_ACTIVATE_BUTTON             1059
#define IDC_NO_PROBLEM_BUTTON           1060
#define IDC_OTHER_GOODNESS_LINK         1061
#define ID_POPUP_EXITBUMPTOP            40002
#define ID_POPUP_EDITSETTINGS           40003
#define ID_POPUP_RESETBUMPTOPLAYOUT     40004
#define ID_POPUP_SENDFEEDBACK           40005
#define ID_POPUP_SHOWBUMPTOP            40006
#define ID_POPUP_REVEALWINDOWSDESKTOP   40007
#define ID_POPUP_S                      40008
#define ID_POPUP_TOGGLEWALLS            40009
#define ID_POPUP_RESETVIEW              40010
#define ID_POPUP_INFINITEDESKTOPTOGGLE  40011
#define ID_POPUP_INFINITEBUMPTOPTOGGLE  40012
#define ID_POPUP_LAUNCHBUMPTOPONSTARTUP 40013
#define ID_POPUP_SHOWEMAILTARGET        40014
#define ID_POPUP_SHOWPRINTERTARGET      40015
#define ID_POPUP_ANTIALIASING           40017
#define ID_POPUP_TEST                   40018
#define ID_POPUP_ENABLEANTI             40019
#define ID_POPUP_VISITBUMPTOPBETAHQ     40020
#define ID_POPUP_BUMPTOPBETAHQ          40021
#define ID_POPUP_BUYBUMPTOPNOW          40022
#define ID_POPUP_INVITEFRIENDSTOBUMPTOP 40023
#define ID_POPUP_INVITEFRIENDS          40024
#define ID_POPUP_GOPRO                  40025
#define ID_POPUP_RUN_TUTORIAL           40026
#define ID_POPUP_UPDATE                 40027
#define IDC_UPDATE_SCREENSHOT           -1
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         40028
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
